title: Android FAQ
subtitle: Android - Frequently Asked Question

url: "https://pro-panda.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
  - name: "Github Repo"
    absolute-link: "https://github.com/irlogcat/Android-FAQ"
